### ISSUE TITLE
dataset is incomplete

### ISSUE THREAD

**Issue by wanglu1214** [khaitran22/CDER#2]
Hello, author. The dataset you made public is incomplete. Could you please share the remaining datasets with me? Thank you.
The following files are missing:
train distant.json
meta
-rel2id.json
-rel info.json

**Comment by khaitran22** [comment]
You can find those files from [this link](https://drive.google.com/drive/folders/1c5-0YwnoJx8NS6CV2f-NoTHR__BdkNqw). 
Please note that the `meta` folder doesn't exist in this original Drive folder. You can download individual files and place them under `meta` folder by following the expected structure.
